CREATE DATABASE entry_task;

USE entry_task;

CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(255) UNIQUE NOT NULL,
	nickname VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	photo VARCHAR(255)
);