CREATE DATABASE IF NOT EXISTS entry_task;

CREATE TABLE IF NOT EXISTS entry_task.users (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(255) UNIQUE NOT NULL,
	nickname VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	photo VARCHAR(255)
);